### ISSUE TITLE
ValueError: Output tensors to a Model must be the output of a TensorFlow `Layer` (thus holding past layer metadata). Found: Tensor("Softmax:0", shape=(?, 88, 46), dtype=float32)

### ISSUE THREAD

**Issue by Hedibouchelliga** [NinV/Korean-License-Plate-Recognition#1]
Hello there  can you please help me to overcome this error 

I'm just trying to run the demo

**Comment by NinV** [comment]
Hi, I tested the code with TensorFlow 1.15 and 2.1.0 and It works fine. I can reproduce the error by using TensorFlow 1.13.1. So please check your TensorFlow version (should be 1.15 or 2). I also tested the code with Tensorflow 1.14 but I have a problem when training the model **_without_** the flag --save_weights_only. I hope this will help
