### ISSUE TITLE
What labeling tool did you use? Or How can I change your code to be trained on pascalvoc format dataset?

### ISSUE THREAD

**Issue by bled214** [NinV/Korean-License-Plate-Recognition#3]
I’m trying to train your code on my own dataset. But your labeling style is kind of different. What labeling tool did you use? Or I’m familiar with tzutalin/labelImg. How can I change your code to be trained on pascalvoc format dataset?

**Comment by bled214** [comment]
I think I figure it out.

**Comment by Amuqeet09** [comment]
@bled214 Could you please share , how did you figure it out?
