### ISSUE TITLE
your model's network architectureis are different from paper's

### ISSUE THREAD

**Issue by zhang787jun** [NinV/Korean-License-Plate-Recognition#8]
your model's network architectureis are different from paper's

**Comment by NinV** [comment]
I used the code [on Openvino](https://github.com/openvinotoolkit/training_extensions/tree/develop/tensorflow_toolkit/lpr). I haven't seen any differences.

**Comment by zhang787jun** [comment]
Wow，find another version ! paper "LPRNet: License Plate Recognition via Deep Neural Networks." [pdf] 's network architectureis show as follow (https://arxiv.org/pdf/1806.10447.pdf)  ![image](https://user-images.githubusercontent.com/51014996/103891500-e9e98580-5124-11eb-82da-aff9ef318ab4.png)
